blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/${{ github.repository_owner }}/dotblue/discussions
    about: For open-ended questions and ideas, prefer Discussions over issues.
