// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domains/im/binding_service.go

// Package im is a generated GoMock package.
package im

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockbindingRepository is a mock of bindingRepository interface.
type MockbindingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbindingRepositoryMockRecorder
}

// MockbindingRepositoryMockRecorder is the mock recorder for MockbindingRepository.
type MockbindingRepositoryMockRecorder struct {
	mock *MockbindingRepository
}

// NewMockbindingRepository creates a new mock instance.
func NewMockbindingRepository(ctrl *gomock.Controller) *MockbindingRepository {
	mock := &MockbindingRepository{ctrl: ctrl}
	mock.recorder = &MockbindingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbindingRepository) EXPECT() *MockbindingRepositoryMockRecorder {
	return m.recorder
}

// CreateBinding mocks base method.
func (m *MockbindingRepository) CreateBinding(ctx context.Context, record bindingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBinding", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBinding indicates an expected call of CreateBinding.
func (mr *MockbindingRepositoryMockRecorder) CreateBinding(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBinding", reflect.TypeOf((*MockbindingRepository)(nil).CreateBinding), ctx, record)
}

// DeleteBinding mocks base method.
func (m *MockbindingRepository) DeleteBinding(ctx context.Context, enterpriseID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinding", ctx, enterpriseID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinding indicates an expected call of DeleteBinding.
func (mr *MockbindingRepositoryMockRecorder) DeleteBinding(ctx, enterpriseID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinding", reflect.TypeOf((*MockbindingRepository)(nil).DeleteBinding), ctx, enterpriseID, id)
}

// GetBinding mocks base method.
func (m *MockbindingRepository) GetBinding(ctx context.Context, enterpriseID, id string) (*bindingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinding", ctx, enterpriseID, id)
	ret0, _ := ret[0].(*bindingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinding indicates an expected call of GetBinding.
func (mr *MockbindingRepositoryMockRecorder) GetBinding(ctx, enterpriseID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinding", reflect.TypeOf((*MockbindingRepository)(nil).GetBinding), ctx, enterpriseID, id)
}

// ListBindingsByConnection mocks base method.
func (m *MockbindingRepository) ListBindingsByConnection(ctx context.Context, enterpriseID, connectionID string) ([]bindingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindingsByConnection", ctx, enterpriseID, connectionID)
	ret0, _ := ret[0].([]bindingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindingsByConnection indicates an expected call of ListBindingsByConnection.
func (mr *MockbindingRepositoryMockRecorder) ListBindingsByConnection(ctx, enterpriseID, connectionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindingsByConnection", reflect.TypeOf((*MockbindingRepository)(nil).ListBindingsByConnection), ctx, enterpriseID, connectionID)
}

// UpdateBinding mocks base method.
func (m *MockbindingRepository) UpdateBinding(ctx context.Context, record bindingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBinding", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBinding indicates an expected call of UpdateBinding.
func (mr *MockbindingRepositoryMockRecorder) UpdateBinding(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBinding", reflect.TypeOf((*MockbindingRepository)(nil).UpdateBinding), ctx, record)
}

// MockbindingConnectionReader is a mock of bindingConnectionReader interface.
type MockbindingConnectionReader struct {
	ctrl     *gomock.Controller
	recorder *MockbindingConnectionReaderMockRecorder
}

// MockbindingConnectionReaderMockRecorder is the mock recorder for MockbindingConnectionReader.
type MockbindingConnectionReaderMockRecorder struct {
	mock *MockbindingConnectionReader
}

// NewMockbindingConnectionReader creates a new mock instance.
func NewMockbindingConnectionReader(ctrl *gomock.Controller) *MockbindingConnectionReader {
	mock := &MockbindingConnectionReader{ctrl: ctrl}
	mock.recorder = &MockbindingConnectionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbindingConnectionReader) EXPECT() *MockbindingConnectionReaderMockRecorder {
	return m.recorder
}

// GetConnection mocks base method.
func (m *MockbindingConnectionReader) GetConnection(ctx context.Context, enterpriseID, id string) (Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, enterpriseID, id)
	ret0, _ := ret[0].(Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockbindingConnectionReaderMockRecorder) GetConnection(ctx, enterpriseID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockbindingConnectionReader)(nil).GetConnection), ctx, enterpriseID, id)
}
